-- AlterTable
ALTER TABLE "DemoUser" ALTER COLUMN "createdAt" DROP NOT NULL,
ALTER COLUMN "createdAt" DROP DEFAULT,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "demoDate" DROP NOT NULL,
ALTER COLUMN "demoDate" DROP DEFAULT,
ALTER COLUMN "demoDate" SET DATA TYPE TIMESTAMP(3);
